logging:
  pattern:
    console: "[Kafka Core Producer] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  application:
    name: kafka-core-producer
  main:
    banner-mode: off
    log-startup-info: false
  jackson:
    date-format: yyyy-MM-dd
    bootstrap-servers: "localhost:9092"
    properties:
#      signifie que le système conserve les 3 derniers échantillons de métriques pour calculer les statistiques.
      metrics:
        num:
          samples: 3